"""QF User OAuth2 Authorization Code flow for per-user API access."""

import logging
from datetime import datetime, timedelta
from typing import Any, Dict

import httpx
from fastapi import HTTPException

from app.config import settings
from app.db.supabase import supabase_client

logger = logging.getLogger(__name__)

# QF OAuth2 scopes for User APIs
QF_USER_SCOPES = (
    "streaks:read streaks:write "
    "activity_days:read activity_days:write "
    "notes:read notes:write "
    "rooms:read rooms:write "
    "posts:read posts:write "
    "goals:read goals:write "
    "reading_sessions:read reading_sessions:write"
)


def get_qf_authorization_url(state: str) -> str:
    """
    Build QF OIDC authorization URL for user to grant scopes.

    Args:
        state: Random state token for CSRF protection (generated by caller)

    Returns:
        Full authorization URL to redirect user to
    """
    callback_url = f"{settings.frontend_url}/auth/qf-callback"
    
    auth_url = (
        f"{settings.qf_oauth2_base_url}/oauth2/authorize"
        f"?response_type=code"
        f"&client_id={settings.qf_client_id}"
        f"&redirect_uri={callback_url}"
        f"&scope={QF_USER_SCOPES}"
        f"&state={state}"
    )
    
    logger.debug("Generated QF authorization URL (state=%s)", state)
    return auth_url


async def exchange_code_for_token(code: str) -> Dict[str, Any]:
    """
    Exchange authorization code for access token via OAuth2.

    Args:
        code: Authorization code from QF callback

    Returns:
        Token response with access_token, expires_in, token_type

    Raises:
        HTTPException(400): Code exchange failed
    """
    callback_url = f"{settings.frontend_url}/auth/qf-callback"
    
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{settings.qf_oauth2_base_url}/oauth2/token",
                auth=(settings.qf_client_id, settings.qf_client_secret),
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                data={
                    "grant_type": "authorization_code",
                    "code": code,
                    "redirect_uri": callback_url,
                },
                timeout=10,
            )
            response.raise_for_status()
            token_data = response.json()
            logger.info("QF OAuth2 code exchange successful")
            return token_data
    except httpx.HTTPError as e:
        logger.error("QF OAuth2 code exchange failed: %s", str(e))
        raise HTTPException(
            status_code=400, detail="QF OAuth2 code exchange failed"
        ) from e


async def store_user_qf_token(user_id: str, token_data: Dict[str, Any]) -> None:
    """
    Store QF user access token in profiles table.

    Args:
        user_id: Supabase user ID (UUID)
        token_data: Token response with access_token and expires_in

    Raises:
        HTTPException(500): Database error
    """
    try:
        access_token = token_data["access_token"]
        expires_in = token_data.get("expires_in", 3600)
        expires_at = datetime.utcnow() + timedelta(seconds=expires_in)

        supabase_client.table("profiles").update(
            {
                "qf_access_token": access_token,
                "qf_token_expires_at": expires_at.isoformat(),
            }
        ).eq("id", user_id).execute()

        logger.info("Stored QF token for user %s (expires in %d seconds)", user_id, expires_in)

    except Exception as e:
        logger.error("Failed to store QF token for user %s: %s", user_id, str(e))
        raise HTTPException(status_code=500, detail="Failed to store QF token") from e


async def get_user_qf_token(user_id: str) -> str:
    """
    Retrieve QF access token for user (with expiry check).

    Falls back to test token if configured (for demo without live OAuth).

    Args:
        user_id: Supabase user ID (UUID)

    Returns:
        QF access token string

    Raises:
        HTTPException(403): Token not connected or expired
        HTTPException(500): Database error
    """
    # Fallback for demo/testing
    if settings.qf_test_user_token:
        logger.debug("Using QF test user token (configured in .env)")
        return settings.qf_test_user_token

    try:
        profile_response = supabase_client.table("profiles").select(
            "qf_access_token,qf_token_expires_at"
        ).eq("id", user_id).execute()

        if not profile_response.data:
            logger.warning("Profile not found for user: %s", user_id)
            raise HTTPException(status_code=404, detail="Profile not found")

        profile = profile_response.data[0]
        access_token = profile.get("qf_access_token")
        expires_at = profile.get("qf_token_expires_at")

        # Check if token is set and not expired
        if not access_token:
            logger.warning("QF account not connected for user: %s", user_id)
            raise HTTPException(
                status_code=403,
                detail="QF account not connected. Please reconnect.",
            )

        if expires_at:
            expiry_dt = datetime.fromisoformat(expires_at)
            if datetime.utcnow() > expiry_dt:
                logger.warning("QF token expired for user: %s", user_id)
                raise HTTPException(
                    status_code=403,
                    detail="QF token expired. Please reconnect.",
                )

        logger.debug("Retrieved valid QF token for user: %s", user_id)
        return access_token

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Failed to retrieve QF token for user %s: %s", user_id, str(e))
        raise HTTPException(status_code=500, detail="Failed to retrieve QF token") from e
